global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: airflow-statsd-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["airflow-statsd-exporter.airflow.svc:9102"]
        labels:
          airflow_id: "airflow"
