apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: airflow-statsd
  namespace: airflow
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
  - port: 9102
    scheme: http
    interval: 30s
    path: /metrics
  selector:
    matchLabels:
      component: statsd
      release: airflow