apiVersion: v1
kind: ConfigMap
metadata:
  name: statsd-exporter-config
  namespace: airflow
data:
  statsd_mapping.yml: |
    mappings:
    - match: airflow.dagrun.dependency-check.*
      name: airflow_dagrun_dependency_check
      labels:
        dag_id: "$1"
    - match: airflow.dag.*.*.duration
      name: airflow_dag_task_duration
      labels:
        dag_id: "$1" 
        task_id: "$2"
    - match: airflow.dag_processing.last_runtime.*
      name: airflow_dag_processing_last_runtime
      labels:
        dag_file: "$1"
    - match: airflow.executor.open_slots
      name: airflow_executor_open_slots
    - match: airflow.executor.queued_tasks
      name: airflow_executor_queued_tasks
    - match: airflow.executor.running_tasks
      name: airflow_executor_running_tasks
    - match: airflow.scheduler.heartbeat
      name: airflow_scheduler_heartbeat
    - match: airflow.ti.start.*.*
      name: airflow_ti_start
      labels:
        dag_id: "$1"
        task_id: "$2" 
    - match: airflow.ti.finish.*.*.*
      name: airflow_ti_finish
      labels:
        dag_id: "$1"
        task_id: "$2"
        state: "$3"