executor: KubernetesExecutor
airflowVersion: "2.10.5"

images:
  airflow:
    repository: apache/airflow
    tag: "2.10.5"
    pullPolicy: IfNotPresent

config:
  core:
    executor: KubernetesExecutor
    fernet_key: "UldaM1dEZGlZVzVuZERCeVlrUjBSR2xHTTNsR1prdGtjWE5EYUhONWNYaz0="
    dags_are_paused_at_creation: true
    load_examples: false
    # Explicitly specify the database connection to use airflow user
    sql_alchemy_conn: "postgresql+psycopg2://airflow:airflow@airflow-postgresql:5432/airflow"
  database:
    # Override any default database connection settings
    sql_alchemy_conn: "postgresql+psycopg2://airflow:airflow@airflow-postgresql:5432/airflow"
  api:
    auth_backends: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
  scheduler:
    enable_health_check: true
  metrics:
    statsd_on: true
    statsd_host: airflow-statsd.airflow.svc.cluster.local
    statsd_port: 9125
    statsd_prefix: airflow
    metrics_use_pattern_match: false
    otel_on: false
  kubernetes:
    # Kubernetes executor configuration
    namespace: airflow
    worker_container_repository: apache/airflow
    worker_container_tag: "2.10.5"
    worker_pods_creation_batch_size: 1
    worker_service_account_name: airflow-worker
    delete_worker_pods: true
    delete_worker_pods_on_success: false
    delete_worker_pods_on_failure: false

webserverSecretKey: "UldaM1dEZGlZVzVuZERCeVlrUjBSR2xHTTNsR1prdGtjWE5EYUhONWNYaz0="

# Override the data connection for all components
data:
  metadataConnection:
    user: airflow
    pass: airflow
    protocol: postgresql
    host: airflow-postgresql
    port: 5432
    db: airflow

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/samuel-aka-viana/airflow-prometheus.git
    branch: main
    subPath: dags

logs:
  persistence:
    enabled: false

postgresql:
  enabled: true
  auth:
    postgresPassword: airflow
    username: airflow
    password: airflow
    database: airflow
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Redis is not needed with KubernetesExecutor
redis:
  enabled: false

scheduler:
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

webserver:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  service:
    type: ClusterIP
    ports:
      - name: airflow-ui
        port: 8080
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    password: admin
    email: admin@example.com
  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 60
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 6
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 12

triggerer:
  enabled: true
  replicas: 1

statsd:
  enabled: false

migrateDatabaseJob:
  enabled: true

cleanup:
  enabled: true

# ServiceAccount and RBAC for KubernetesExecutor worker pods
serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - "pods"
        - "pods/log"
      verbs:
        - "create"
        - "get"
        - "delete"
        - "list"
        - "watch"